# k8s-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usap-db-creds
type: Opaque
data:
  # Base64 values for your Docker Compose setup:
  # 'db' -> ZGI=
  # 'edoc' -> ZWRvYw==
  # 'user' -> dXNlcg==
  # 'password' -> cGFzc3dvcmQ=
  DB_HOST: ZGI=
  DB_NAME: ZWRvYw==
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
