apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  # The values must be base64 encoded strings
  # Example: echo -n 'root' | base64
  root-password: cm9vdAo= # Base64 of 'root'
  password: cGFzc3dvcmQK # Base64 of 'password'