name: Docker CI Pipeline

on:
  push:
    branches:
      - phase-0
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/usap-web # Replace 'usap-web' with your desired image name
          tags: |
            type=sha,prefix=
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Looks for the Dockerfile in the root directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}